on:
  push:
    branches:
    - main

jobs:
  generate_release:
    name: Generate pre-release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install web-ext
        run: npm install --global web-ext
      - name: Sign extension
        env:
          API_ISSUER: ${{ secrets.API_ISSUER }}
          API_KEY: ${{ secrets.API_KEY }}
        run: web-ext sign --api-key="${API_ISSUER}" --api-secret="${API_KEY}" && cd web-ext-artifacts && mv *.xpi extension.xpi && cd ..
      - name: Set Release Tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          release_name: Pre-release from ${{ steps.vars.outputs.sha_short }}
          body: Autogenerated release.
          draft: false
          prerelease: true
      - name: Upload Release Assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./web-ext-artifacts/extension.xpi
          asset_name: extension.xpi
          asset_content_type: application/x-xpinstall
